version: "3"
services:
  animal_reg:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    networks:
      - mynetwork
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: animal
      MYSQL_DATABASE: registration_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
