services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventSubscriber\DrugAssignedSubscriber:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\DrugRemovedSubscriber:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_subscriber' }